version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: online-book-store-db
    environment:
      MYSQLDB_DATABASE: ${DB_NAME}
      MYSQLDB_USER: ${DB_USERNAME}
      MYSQLDB_PASSWORD: ${DB_PASSWORD}
      MYSQLDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: online-book-store-app
    ports:
      - "${APP_PORT}:8080"
    environment:
      MYSQLDB_HOST: ${DB_HOST}
      MYSQLDB_PORT: ${DB_PORT}
      MYSQLDB_NAME: ${DB_NAME}
      MYSQLDB_USERNAME: ${DB_USERNAME}
      MYSQLDB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      mysql-db:
        condition: service_healthy

volumes:
  mysql_data: