version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: online-book-store-db
    environment:
      MYSQL_DATABASE: ${MYSQLDB_NAME}
      MYSQL_USER: ${MYSQLDB_USERNAME}
      MYSQL_PASSWORD: ${MYSQLDB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
    ports:
      - "${MYSQLDB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQLDB_ROOT_PASSWORD}"]
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: online-book-store-app
    ports:
      - "${APP_PORT}:8080"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      mysql-db:
        condition: service_healthy

volumes:
  mysql_data: