spring.application.name=Online-Book-Store-App

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/ \
    ${DB_NAME:Online_Book_Store}?serverTimezone=UTC
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.expiration=86400000
jwt.secret=${JWT_SECRET:xyfgvyuibyicrtyxtybuinmiopnuivtyixryucubuiuc7tui2137}
